### ISSUE TITLE
some question

### ISSUE THREAD

**Issue by YUZHIWANG-bug** [genbing99/MTSN-Spot-ME-MaE#2]
Dear author, I want to ask how to obtain the dataset, as shown below：
<img width="608" alt="image" src="https://user-images.githubusercontent.com/72587415/199155202-ee150b59-53e5-4c89-bdf1-972b20a0ed3b.png">

**Comment by genbing99** [comment]
The download link is provided in the README,
https://drive.google.com/file/d/1Cn4rux-Hwrt6E1LWO3VL3ddNqOwmgP71/view

**Comment by YUZHIWANG-bug** [comment]
> The download link is provided in the README, https://drive.google.com/file/d/1Cn4rux-Hwrt6E1LWO3VL3ddNqOwmgP71/view
Oh, thank you for your reply. I ignored it. I'm sorry to bother you. Thank you very much!
