### ISSUE TITLE
代码训练结果复现

### ISSUE THREAD

**Issue by bleakie** [genbing99/MTSN-Spot-ME-MaE#5]
您好，我尝试重新训练了您的代码，使用您的训练集，1/4做验证，但是发现f1-score非常低，和论文不符，请问可能是什么原因造成的呢？

**Comment by genbing99** [comment]
Hi, it is hard to tell because the evaluation method you used is different from the LOSO evaluation that is reported in the paper.
I have uploaded the evaluation part on MEGC 2021 benchmark.  Please refer to this #3.
