### ISSUE TITLE
about megc2022-processed-data

### ISSUE THREAD

**Issue by Vebrun** [genbing99/MTSN-Spot-ME-MaE#7]
Hello, I am not very clear how your processed data is obtained.  CAS_Test_cropped_dataset_k1.pkl and CAS_Test_cropped_dataset_k6.pkl are came from  here? I found that they are the same size（28*28*3）
![image](https://user-images.githubusercontent.com/95894804/216281732-c2407896-4d23-4d9a-afc0-6157e77ab3a7.png)

**Comment by genbing99** [comment]
Hi, the processed data refers to the optical flow features (red color box)
![image](https://user-images.githubusercontent.com/58872276/216642766-f99dfcc7-fd25-4f95-9430-e059ddc667a9.png)

You can check out this Jupyter Notebook for the computation of optical flow features.
https://drive.google.com/file/d/1G94Cwn-FKEkBtIjN_8fKWNXoBrVaM4PX/view?usp=sharing
